### ISSUE TITLE
Service's doc/descriptions

### ISSUE THREAD

**Issue by raiman79** [brutusin/jsonsrv#1]
I really miss the chance of providing some kind of auto-doc/descriptions, when developing my services, that will help the end user to use them

**Comment by idelvall** [comment]
Hi raiman :)
Yes, its a nice feature, that definitely will improve services maintenance and usability. Now I wondering what is the best place to implement it, in jsonsrv (raw application/json) responses or in jsonsrv-human-renderer (rich text/html) responses.
Also the type of the payload txt, markdown,...
Any ideas?

**Comment by idelvall** [comment]
Hi, I have just implemented this.

* Upgrade jsonsrv to 2.3.0
* Upgrade jsonsrv-human-render to 1.2.0
* Help at: https://github.com/brutusin/jsonsrv/blob/master/README.md#adding-services-documentation
